parser: babel-eslint

env:
  browser: true

extends:
  - airbnb
  - prettier
  - prettier/react

plugins:
  - react
  - prettier

rules:
  prettier/prettier:
    - error

settings:
  import/resolver:
    webpack:
      config: 'config/webpack/development.js'
